version: '3.9'
services:
  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: khuzin/m1p-dask:latest
    command: dask scheduler
    volumes:
      - ../data:/home/khuzin/Projects/2025-Project-188/data:rw
      - ./src:/opt/app/src:rw
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - dask-net

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: khuzin/m1p-dask:latest
    command: dask worker tcp://scheduler:8786
    depends_on:
      - scheduler
    networks:
      - dask-net
    volumes:
      - ../data:/home/khuzin/Projects/2025-Project-188/data:rw
      - ./src:/opt/app/src:rw
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 6G

  db:
    image: postgres:17
    container_name: postgres
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     "khuzin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB:       "project"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khuzin -d project"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  dask-net:
    driver: bridge
