[project]
name = "pro-1-experiments"
version = "1.0.0"
description = ""
authors = [
    {name = "Eldar Khuzin",email = "khuzin.e@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask[complete] (>=2024.0.0,<2025.0.0)",
    "geopandas (>=1.0.1,<2.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "marimo (>=0.11.21,<0.12.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "nbformat (>=5.10.4,<6.0.0)",
    "darts (>=0.34.0,<0.35.0)",
    "xarray (>=2025.1.2,<2026.0.0)",
    "netcdf4 (>=1.7.2,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "fastcluster (>=1.2.6,<2.0.0)",
    "shap (>=0.47.1,<0.48.0)",
    "xgboost (>=2.0.0,<3.0.0)",
    "fastparquet (>=2024.11.0,<2025.0.0)",
    "bokeh (>=3.7.2,<4.0.0)",
    "jupytext (>=1.17.1,<2.0.0)",
    "polars (>=1.29.0,<2.0.0)",
]

[tool.poetry]
packages = [
    {include = "utils", from = "src"}
]
package-mode=true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.marimo.runtime]
output_max_bytes = 20_000_000


